<?php

function ablecore_install()
{
	// Set the weight to a much lower value so that hook_menu() is run before other modules.
	db_query("UPDATE {system} SET weight = -89 WHERE name = 'ablecore' AND type = 'module'");
}

function ablecore_update_7000()
{
	// Set the weight to a much lower value so that hook_menu() is run before other modules.
	db_query("UPDATE {system} SET weight = -89 WHERE name = 'ablecore' AND type = 'module'");
}
