<?php

namespace AbleCore\Install\Helpers\Fields;

use AbleCore\Install\Helpers\Field;
use AbleCore\Install\Helpers\FieldTypes;

class EntityReferenceField extends Field {

	public function __construct($field_name, array $definition)
	{
		parent::__construct($field_name, $definition);

		$this->setSetting('target_type', 'node');
		$this->setSetting('handler', 'base');
		$this->setSetting('handler_settings', array(
			'target_bundles' => array(),
			'sort' => array('type' => 'none'),
		));
	}

	public function save()
	{
		if (empty($this->definition['settings']['handler_settings']['target_bundles'])) {
			throw new \Exception('The field ' . $this->getName() . ' does not reference any target bundles.');
		}

		return parent::save(); // TODO: Change the autogenerated stub
	}

	/**
	 * Defines the bundles this field references.
	 *
	 * @param array  $bundles An array of bundles this entity reference references.
	 * @param string $type    The type of entity to reference.
	 *
	 * @return $this
	 */
	public function references(array $bundles = array(), $type = 'node')
	{
		$this->setSetting('target_type', $type);
		$this->definition['settings']['handler_settings']['target_bundles'] = drupal_map_assoc($bundles);
		return $this;
	}

	public function setType($type = FieldTypes::ENTITY_REFERENCE)
	{
		return parent::setType($type);
	}
}
